# Basic
hard_tabs = true
max_width = 120
use_small_heuristics = "Max"
single_line_if_else_max_width = 80

# Imports
imports_granularity = "Crate"
group_imports = "Preserve"
reorder_imports = true

# Consistency
newline_style = "Unix"

# Format comments
comment_width = 120
wrap_comments = true

# Misc
chain_width = 100
spaces_around_ranges = false
binop_separator = "Back"
reorder_impl_items = false
# reorder_impl_items = true
match_arm_leading_pipes = "Preserve"
match_arm_blocks = false
# match_arm_blocks = true
match_block_trailing_comma = true
trailing_comma = "Vertical"
trailing_semicolon = false
# trailing_semicolon = true
use_field_init_shorthand = true
edition = "2021"
